import { useEffect,useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { AlertTriangle, ArrowRight, CheckCircle2 } from 'lucide-react'
import { getDashboard } from '../lib/data'
import { brl,pct } from '../lib/format'
import type { AlertItem,KPISet,RevenuePoint,TeamPerformance } from '../lib/types'
import { Badge,MetricCard,Panel } from '../components/ui'

export function Dashboard(){
 const [data,setData]=useState<{kpis:KPISet;revenue:RevenuePoint[];teams:TeamPerformance[];alerts:AlertItem[]} | null>(null)
 useEffect(()=>{getDashboard().then(setData)},[])
 if(!data)return <div className="glass rounded-3xl p-10 text-center text-sm text-white/45">Carregando indicadores...</div>
 const {kpis,revenue,teams,alerts}=data
 return <div className="space-y-4">
  <div className="metric-grid"><MetricCard label="Receita realizada" value={brl(kpis.revenueRealized,true)} detail={`Meta ${brl(kpis.targetRevenue,true)}`} trend={4.8} tone="positive"/><MetricCard label="Conversão" value={pct(kpis.conversionRate)} detail="Lead → venda" trend={-1.4} tone="warning"/><MetricCard label="Pipeline" value={brl(kpis.pipelineValue,true)} detail={`Forecast ${brl(kpis.revenueForecast,true)}`} trend={2.7}/><MetricCard label="ROI operacional" value={`${kpis.roi.toFixed(2)}x`} detail={`Custo ${brl(kpis.operationalCost,true)}`} trend={6.1} tone="positive"/></div>
  <div className="grid gap-4 xl:grid-cols-[1.65fr_1fr]">
   <Panel title="Evolução de receita" subtitle="Realizado, previsão e meta"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue}><defs><linearGradient id="fillRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#34d399" stopOpacity={.25}/><stop offset="95%" stopColor="#34d399" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="period" stroke="rgba(255,255,255,.3)" tickLine={false} axisLine={false}/><YAxis stroke="rgba(255,255,255,.3)" tickLine={false} axisLine={false} tickFormatter={(v)=>`${Math.round(v/1000000)}M`}/><Tooltip contentStyle={{background:'#15141b',border:'1px solid rgba(255,255,255,.1)',borderRadius:16}} formatter={(v:any)=>brl(Number(v),true)}/><Area type="monotone" dataKey="realized" stroke="#34d399" fill="url(#fillRevenue)" strokeWidth={2.3}/><Area type="monotone" dataKey="forecast" stroke="#60a5fa" fill="transparent" strokeDasharray="5 5"/><Area type="monotone" dataKey="target" stroke="#fbbf24" fill="transparent" strokeDasharray="2 5"/></AreaChart></ResponsiveContainer></div></Panel>
   <Panel title="Alertas de inteligência" subtitle="O que exige decisão agora"><div className="space-y-2">{alerts.slice(0,4).map(a=><div key={a.id} className="rounded-2xl bg-white/[.035] p-3.5 ring-1 ring-white/7"><div className="flex items-start gap-3"><div className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-xl ${a.severity==='high'||a.severity==='critical'?'bg-rose-400/10 text-rose-300':'bg-amber-400/10 text-amber-300'}`}>{a.severity==='low'?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold">{a.title}</p><Badge tone={a.severity==='high'?'red':'amber'}>{a.confidence}%</Badge></div><p className="mt-1 text-[11px] leading-4 text-white/42">{a.recommendedAction}</p></div></div></div>)}</div></Panel>
  </div>
  <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
   <Panel title="Conversão por equipe" subtitle="Comparação para localizar o desvio"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-white/35"><tr><th className="pb-3">Equipe</th><th>Conversão</th><th>Receita</th><th>Pipeline</th><th>Capacidade</th></tr></thead><tbody>{teams.map(t=><tr key={t.id} className="border-t border-white/7"><td className="py-3 font-medium">{t.team}</td><td className={t.conversion<7?'text-rose-300':'text-emerald-300'}>{pct(t.conversion)}</td><td>{brl(t.revenue,true)}</td><td>{brl(t.pipeline,true)}</td><td><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-emerald-400" style={{width:`${Math.min(100,t.capacity)}%`}}/></div>{t.capacity}%</div></td></tr>)}</tbody></table></div></Panel>
   <Panel title="Pulso da operação"><div className="space-y-3">{[['Produtividade',`${kpis.productivity.toFixed(1)}%`,'Acima da referência'],['Agentes ativos',String(kpis.activeAgents),'Capacidade atual'],['Aging médio',`${kpis.avgAgingDays.toFixed(1)} dias`,'Pipeline aberto'],['Forecast de fechamento',brl(kpis.revenueForecast,true),'106% da meta']].map(([a,b,c])=><div key={a} className="flex items-center justify-between rounded-2xl bg-white/[.035] px-4 py-3 ring-1 ring-white/7"><div><p className="text-xs font-medium">{a}</p><p className="mt-1 text-[10px] text-white/35">{c}</p></div><div className="flex items-center gap-2"><span className="text-sm font-semibold">{b}</span><ArrowRight size={14} className="text-white/25"/></div></div>)}</div></Panel>
  </div>
 </div>
}
