import { useEffect,useMemo,useState } from 'react'
import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,Bar,BarChart,Cell } from 'recharts'
import { AlertTriangle,ArrowRight,CheckCircle2,Clock3,Database,ShieldCheck,Sparkles,Target,TrendingDown,TrendingUp } from 'lucide-react'
import { getDashboard,getDecisionCockpit } from '../lib/data'
import { brl,pct } from '../lib/format'
import type { DecisionCockpit,KPISet,RevenuePoint,TeamPerformance } from '../lib/types'
import { Badge,Button,Panel } from '../components/ui'

type DashboardData={kpis:KPISet;revenue:RevenuePoint[];teams:TeamPerformance[]}

export function Dashboard(){
 const [base,setBase]=useState<DashboardData|null>(null)
 const [cockpit,setCockpit]=useState<DecisionCockpit|null>(null)
 const [period,setPeriod]=useState('Mês atual')
 const [scope,setScope]=useState('Todas as operações')
 useEffect(()=>{Promise.all([getDashboard(),getDecisionCockpit()]).then(([d,c])=>{setBase({kpis:d.kpis,revenue:d.revenue,teams:d.teams});setCockpit(c)})},[])
 const driverChart=useMemo(()=>cockpit?.drivers.map(d=>({name:d.label,value:d.impact,fill:d.direction==='positive'?'#34d399':'#fb7185'}))??[],[cockpit])
 if(!base||!cockpit)return <div className="glass rounded-3xl p-10 text-center text-sm text-white/45">Carregando central de decisão...</div>
 const {kpis,revenue,teams}=base
 return <div className="space-y-4">
  <div className="glass-soft flex flex-wrap items-center gap-2 rounded-2xl p-2.5">
    <Filter label="Período" value={period} onChange={setPeriod} options={['Hoje','Últimos 7 dias','Mês atual','Trimestre']}/>
    <Filter label="Escopo" value={scope} onChange={setScope} options={['Todas as operações','Vendas','Cobrança','SAC']}/>
    <div className="ml-auto flex items-center gap-2 px-2 text-[10px] text-white/35"><Clock3 size={13}/> Dados consolidados há 4 min</div>
  </div>

  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
    {cockpit.scorecards.map(m=><Scorecard key={m.id} {...m}/>) }
  </div>

  <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
    <Panel title="Prioridades para decisão" subtitle="Ordenadas por severidade, impacto, confiança e urgência" action={<Badge tone="amber">{cockpit.priorities.length} decisões</Badge>}>
      <div className="space-y-2.5">{cockpit.priorities.map((p,i)=><div key={p.id} className="rounded-2xl bg-white/[.035] p-4 ring-1 ring-white/8"><div className="flex items-start gap-3"><div className={`grid size-9 shrink-0 place-items-center rounded-xl text-xs font-bold ${p.severity==='high'||p.severity==='critical'?'bg-rose-400/12 text-rose-300':'bg-amber-400/12 text-amber-300'}`}>0{i+1}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">{p.title}</p><div className="flex gap-1.5"><Badge tone={p.severity==='high'||p.severity==='critical'?'red':'amber'}>{p.dueLabel}</Badge><Badge>{p.confidence}% confiança</Badge></div></div><p className="mt-1 text-[11px] leading-5 text-white/48">{p.whyNow}</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><div className="rounded-xl bg-black/15 px-3 py-2"><p className="text-[9px] uppercase tracking-[.16em] text-white/30">Ação recomendada</p><p className="mt-1 text-[11px] leading-4 text-white/70">{p.action}</p></div><div className="min-w-32 rounded-xl bg-black/15 px-3 py-2 text-right"><p className="text-[9px] uppercase tracking-[.16em] text-white/30">{p.impactLabel}</p><p className="mt-1 text-sm font-semibold">{p.impactValue>1000?brl(p.impactValue,true):p.impactValue}</p><p className="text-[9px] text-white/30">{p.owner}</p></div></div></div></div></div>)}</div>
    </Panel>
    <Panel title="Briefing executivo" subtitle="Leitura gerencial pronta para reunião" action={<Sparkles size={17} className="text-emerald-300"/>}>
      <div className="rounded-2xl bg-emerald-400/[.07] p-4 ring-1 ring-emerald-400/15"><p className="text-sm font-semibold leading-5 text-emerald-50">{cockpit.brief.headline}</p><p className="mt-2 text-[11px] leading-5 text-emerald-50/65">{cockpit.brief.summary}</p></div>
      <div className="mt-3 grid gap-2"><BriefLine icon={<TrendingUp size={14}/>} tone="green" label="Sinais positivos" items={cockpit.brief.positive}/><BriefLine icon={<AlertTriangle size={14}/>} tone="red" label="Riscos" items={cockpit.brief.risks}/><BriefLine icon={<Target size={14}/>} tone="blue" label="Decisões sugeridas" items={cockpit.brief.decisions}/></div>
    </Panel>
  </div>

  <div className="grid gap-4 xl:grid-cols-[1.55fr_.85fr]">
    <Panel title="Receita, forecast e meta" subtitle="Tendência de fechamento com comparação histórica"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue}><defs><linearGradient id="fillRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#34d399" stopOpacity={.28}/><stop offset="95%" stopColor="#34d399" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="period" stroke="rgba(255,255,255,.32)" tickLine={false} axisLine={false}/><YAxis stroke="rgba(255,255,255,.32)" tickLine={false} axisLine={false} tickFormatter={(v)=>`${Math.round(v/1000000)}M`}/><Tooltip contentStyle={{background:'#15141b',border:'1px solid rgba(255,255,255,.1)',borderRadius:16}} formatter={(v:any)=>brl(Number(v),true)}/><Area type="monotone" dataKey="realized" name="Realizado" stroke="#34d399" fill="url(#fillRevenue)" strokeWidth={2.4}/><Area type="monotone" dataKey="forecast" name="Forecast" stroke="#60a5fa" fill="transparent" strokeDasharray="5 5"/><Area type="monotone" dataKey="target" name="Meta" stroke="#fbbf24" fill="transparent" strokeDasharray="2 5"/></AreaChart></ResponsiveContainer></div></Panel>
    <Panel title="Drivers do resultado" subtitle="O que mais explica a variação do período"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={driverChart} margin={{left:8,right:20}}><CartesianGrid stroke="rgba(255,255,255,.05)" horizontal={false}/><XAxis type="number" stroke="rgba(255,255,255,.3)" tickLine={false} axisLine={false}/><YAxis dataKey="name" type="category" width={120} stroke="rgba(255,255,255,.42)" tickLine={false} axisLine={false} tick={{fontSize:10}}/><Tooltip contentStyle={{background:'#15141b',border:'1px solid rgba(255,255,255,.1)',borderRadius:14}} formatter={(v:any)=>`${Number(v)>0?'+':''}${Number(v).toFixed(1)} p.p.`}/><Bar dataKey="value" radius={8}>{driverChart.map((d,i)=><Cell key={i} fill={d.fill}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel>
  </div>

  <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
    <Panel title="Mapa de risco operacional" subtitle="Probabilidade × impacto × exposição financeira"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-white/35"><tr><th className="pb-3">Equipe</th><th>Categoria</th><th>Prob.</th><th>Impacto</th><th>Exposição</th><th>Responsável</th></tr></thead><tbody>{cockpit.risks.map(r=>{const score=r.probability*r.impact;return <tr key={r.id} className="border-t border-white/7"><td className="py-3 font-medium">{r.name}</td><td>{r.category}</td><td>{r.probability}%</td><td>{r.impact}%</td><td className={score>5000?'text-rose-300':'text-amber-300'}>{brl(r.exposure,true)}</td><td className="text-white/45">{r.owner}</td></tr>})}</tbody></table></div></Panel>
    <Panel title="Confiança dos dados" subtitle="Governança incorporada à tomada de decisão"><div className="flex items-center gap-4 rounded-2xl bg-white/[.035] p-4 ring-1 ring-white/8"><div className="relative grid size-24 shrink-0 place-items-center rounded-full border-[9px] border-emerald-400/15"><div className="absolute inset-[-9px] rounded-full border-[9px] border-emerald-400 border-l-transparent border-b-transparent rotate-45"/><div className="text-center"><p className="text-2xl font-semibold">{cockpit.trust.score}</p><p className="text-[9px] uppercase tracking-wider text-white/30">de 100</p></div></div><div className="flex-1 space-y-2"><Trust label="Atualização" value={cockpit.trust.freshness}/><Trust label="Completude" value={cockpit.trust.completeness}/><Trust label="Consistência" value={cockpit.trust.consistency}/></div></div><div className="mt-3 grid grid-cols-2 gap-2"><Info icon={<Database size={15}/>} label="Fontes online" value={`${cockpit.trust.onlineSources}/${cockpit.trust.totalSources}`}/><Info icon={<ShieldCheck size={15}/>} label="Duplicidades" value={String(cockpit.trust.duplicates)}/></div></Panel>
  </div>

  <Panel title="Performance por equipe" subtitle="Resultado, pipeline, conversão e capacidade em uma única visão"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-white/35"><tr><th className="pb-3">Equipe</th><th>Conversão</th><th>Receita</th><th>Pipeline</th><th>Atividades</th><th>Capacidade</th><th></th></tr></thead><tbody>{teams.map(t=><tr key={t.id} className="border-t border-white/7"><td className="py-3 font-medium">{t.team}</td><td className={t.conversion<7?'text-rose-300':'text-emerald-300'}>{pct(t.conversion)}</td><td>{brl(t.revenue,true)}</td><td>{brl(t.pipeline,true)}</td><td>{t.activities}</td><td><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-emerald-400" style={{width:`${Math.min(100,t.capacity)}%`}}/></div>{t.capacity}%</div></td><td><ArrowRight size={14} className="text-white/25"/></td></tr>)}</tbody></table></div></Panel>
 </div>
}

function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="flex items-center gap-2 rounded-xl bg-white/[.035] px-3 py-2 text-[10px] text-white/35 ring-1 ring-white/7"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="bg-transparent text-[11px] font-medium text-white outline-none">{options.map(o=><option className="bg-[#15141b]" key={o}>{o}</option>)}</select></label>}
function Scorecard({label,value,target,forecast,delta,status,confidence,freshness}:any){const dot=status==='healthy'?'bg-emerald-400':status==='attention'?'bg-amber-400':'bg-rose-400';return <div className="rounded-3xl bg-card p-4 ring-1 ring-border"><div className="flex items-start justify-between gap-2"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-muted-foreground">{label}</p><span className={`size-2 rounded-full ${dot}`}/></div><div className="mt-3 flex items-end justify-between gap-2"><p className="text-2xl font-semibold tracking-tight">{value}</p><span className={`inline-flex items-center gap-1 text-[10px] ${delta>=0?'text-emerald-300':'text-rose-300'}`}>{delta>=0?<TrendingUp size={12}/>:<TrendingDown size={12}/>} {Math.abs(delta)}%</span></div><p className="mt-2 text-[11px] text-white/45">{target}</p>{forecast&&<p className="mt-1 text-[10px] text-white/30">{forecast}</p>}<div className="mt-3 flex items-center justify-between border-t border-white/7 pt-2 text-[9px] text-white/28"><span>{confidence}% confiança</span><span>há {freshness}</span></div></div>}
function BriefLine({icon,tone,label,items}:{icon:any;tone:'green'|'red'|'blue';label:string;items:string[]}){const c=tone==='green'?'text-emerald-300 bg-emerald-400/8':tone==='red'?'text-rose-300 bg-rose-400/8':'text-sky-300 bg-sky-400/8';return <div className={`rounded-2xl p-3 ${c}`}><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider">{icon}{label}</div><div className="mt-2 space-y-1.5">{items.slice(0,3).map(i=><p key={i} className="text-[10px] leading-4 text-white/58">• {i}</p>)}</div></div>}
function Trust({label,value}:{label:string;value:number}){return <div><div className="mb-1 flex justify-between text-[9px] text-white/35"><span>{label}</span><span>{value}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/7"><div className="h-full rounded-full bg-emerald-400" style={{width:`${value}%`}}/></div></div>}
function Info({icon,label,value}:{icon:any;label:string;value:string}){return <div className="flex items-center justify-between rounded-2xl bg-white/[.035] px-3 py-3 ring-1 ring-white/7"><div className="flex items-center gap-2 text-[10px] text-white/40">{icon}{label}</div><span className="text-xs font-semibold">{value}</span></div>}
